build:
    nodes:
        php70:
            environment:
                php: 7.0
        php71:
            environment:
                php: 7.1
        php72:
            environment:
                php: 7.2
        php73:
            environment:
                php: 7.3
    tests:
        override:
            -
                command: vendor/bin/phpunit --coverage-clover=build/logs/clover
                coverage:
                    file: build/logs/clover
                    format: php-clover