build:
    nodes:
        analysis:
            dependencies:
                after:
                    - composer require --dev "squizlabs/php_codesniffer=3.2.2"
        php70:
            environment:
                php: 7.0
        php71:
            environment:
                php: 7.1
        php72:
            environment:
                php: 7.2
        php73:
            environment:
                php: 7.3
        php74:
            environment:
                php: 7.4
        php80:
            environment:
                php: 8.0.0RC3
    tests:
        override:
            -
                command: vendor/bin/phpunit --coverage-clover=build/logs/clover
                coverage:
                    file: build/logs/clover
                    format: php-clover
